# Generated by Django 5.2.4 on 2025-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='Black', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.CharField(default='Black', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Black', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='registration',
            field=models.CharField(default='Black', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Black', max_length=100),
        ),
    ]
