# Generated by Django 5.2.4 on 2025-07-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_car_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
    ]
