# Generated by Django 5.2.4 on 2025-07-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_car_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(max_length=100),
        ),
    ]
