# Generated by Django 5.2.4 on 2025-07-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_myimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimagemodel',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.car'),
            preserve_default=False,
        ),
    ]
