# Generated by Django 5.2.4 on 2025-07-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_myimagemodel_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImageModel',
        ),
    ]
